### ISSUE TITLE
[FE] Disable buttons when in loading state

### ISSUE THREAD

**Issue by afazio1** [GTBitsOfGood/canine-assistants#200]
### Description
Ensure that all buttons having a loading state and hover state. 
When a user clicks a button, it usually sends a request to the backend. While this is happening, disable the button. After the we get a response, enable the button again. 
Add tailwind css to give buttons a different color on hover. See Figma for designs. 

An example of this functionality is the Log Modal Save button. Take reference from that.

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i would like to work on this issue if there is no one currently working on it
