### ISSUE TITLE
[FE] Finish Dog Table Page

### ISSUE THREAD

**Issue by afazio1** [GTBitsOfGood/canine-assistants#21]
### Description
Make revisions, finish styling, and add pagination to the dog table page.

### Acceptance Criteria
- [x] Add `Other` column
- [x] Tags link to the log section of the individual dog's page (once we have log endpoints done, we can also link to individual log)
- [x] `Date Of Birth` should turn into `Age`. `Age` in years can be calculated based on date of birth
- [x] Add Filter component and connect it to our search dogs api
- [x] Add pagination so only 10 dogs are visible on the screen (note: we are still retrieving all dogs on page load, just restricting how many appear on the page)
- [x] Styling reflects design documents

### Other Notes
- N/a

**Comment by UZ9** [comment]
Current TODO Changes:
- [x] Dog schema must be adjusted to allow recent log tags to be queried
- [ ] (Low priority) Visual update for when log filter becomes too big (and can't be displayed visually)
- [ ] (Low priority) Slightly adjust padding for filter cards to prevent shift in content 
- [ ] (Low priority) Increase clickable size for pagination buttons
