### ISSUE TITLE
[BE] Update user API endpoints

### ISSUE THREAD

**Issue by afazio1** [GTBitsOfGood/canine-assistants#35]
### Description
Users should be able to update certain parts of their profile. Admins should be able to update user's roles. 

Create an API endpoint `PATCH /api/users` that updates a user in the db. Return the updated user as response `data`. 

### Acceptance Criteria
- [ ] Users should only be able to change personal info in their profile
- [ ] Admin should be able to change all other fields besides personal info and auth generated properties (ie. image, email, etc) for other users
- [ ] Proper error handling

### Other Notes
- Communicate with person doing auth ticket to figure out the auth generated properties

**Comment by jaipise** [comment]
I still need to seed new data into my local db to test these changes but the functionality and logic are all here now
