### ISSUE TITLE
[FE] Add New Dog Form

### ISSUE THREAD

**Issue by afazio1** [GTBitsOfGood/canine-assistants#58]
### Description
Admin want to be able to add dogs to the database. 

Create a new file `pages/dogs/new.jsx`, where a user can enter information about a new dog. 

Implement the page based on the Figma designs. 

Since this is a bigger form, I recommend using `react-hook-form`. 

Here are some things to note:
- clicking the **Add Dog** button on the `/dogs` page should link to `/dogs/new`
- clicking the **Save Dog** button should 
	1. perform client-side form validation using zod
	2. send a request to `POST /api/dogs` with the body being the validated form data
	3. if success, redirect to `/dogs` . If failure, keep state of form and do not redirect
	4. trigger an appropriate toast (react-hot-toast) on success or failure
- clicking **Cancel** should take the user to `/dogs`
- You'll notice **Time of Birth** is not in our mongoose dog model, however it should be combined with **Date of Birth** to produce the value for `dateOfBirth` in the dog model. You'll have to research JS Date formats
- Don't worry about the **Image** upload just yet. You can create the frontend but the backend will be implemented in a later sprint
- **Mother** and **Father** inputs should be searchable *single-select* drop-downs
	- we are using [react-select](https://react-select.com/home) for these type of inputs
	- the options for this dropdown would be all dogs in the db. 
	    - Try to fetch this information only once when the page mounts/loads. Look into https://swr.vercel.app as well. 
	    - Try to narrow the searches when possible ie. only retrieve Female dogs for the Mother dropdown (you will have to edit the `POST /api/dogs/search` endpoint if you want to achieve this. 
- **Instructors** and **Caregivers** should be searchable *multi-select* drop-downs
	- use the same tools mentioned above
- **Maternal Demeanor Prior**, **During**, and **Subsequent** are visually separate form fields, but in the db they are all stored together in the `maternalDemeanor` array on the dog model. 
### Acceptance Criteria
- [ ] Proper error handling
- [ ] Implements Figma designs
- [ ] Proper JS doc comments above functions

### Other Notes
- [react-select optimization resource](https://www.botsplash.com/post/optimize-your-react-select-component-to-smoothly-render-10k-data)

**Comment by UZ9** [comment]
`/dogs/new` would clash with `[id]`, is there another place it should be instead?
