### ISSUE TITLE
Dog table chips grow past their table row

### ISSUE THREAD

**Issue by afazio1** [GTBitsOfGood/canine-assistants#64]
### Description
<img width="1280" alt="Screen Shot 2023-10-22 at 12 05 09 PM" src="https://github.com/GTBitsOfGood/canine-assistants/assets/45372449/f1a21ce0-28ef-4084-9540-a34024d51b70"/>
 I believe this happens when the Recent Log Tags column gets too wide. In the image above, the **Feeding Change** tag should wrap under. 

### Other Notes
- This tag wrapping was done pretty well on the **Add New Log Modal**, so that code could be used for reference

**Comment by UZ9** [comment]
Fixed in ryder-add-new-dog-form
